version: '3.7'
services:
  mcdash:
    image: germannewsmaker/mcdash
    container_name: MCDash
    restart: unless-stopped
    volumes:
      - mcdash:/app/data
    ports:
      - 7865:7865
      - 25565:25565 # Add the necessary port mappings for the minecraft servers
      - 5174:5174
      
volumes:
    mcdash: